name: usland
description: Dynamic Island overlay for Android
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_overlay_window: ^0.3.0
  notification_listener_service: ^0.3.5
  flutter_animate: ^4.2.0
  provider: ^6.1.0
  shared_preferences: ^2.2.0
  google_fonts: ^6.1.0
  package_info_plus: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
